### ISSUE TITLE
sudoers.d file locks me out of the system

### ISSUE THREAD

**Issue by amertner** [fivesixzero/telegraf-pi-bash#3]
Thank you for this, it's just what I needed!

Unfortunately, after I copied the 040-telegraf file to sudoers.d, I can no longer sudo anything - I get this error:
```
>>> /etc/sudoers.d/040-telegraf: syntax error near line 3 <<<
sudo: parse error in /etc/sudoers.d/040-telegraf near line 3
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

```
Line 3 of the file is this:
`Defaults!RPIDATA !logfile, !syslog, !pam_session
`

I'm not sure what to do - is there a workaround, or do I need to boot from another image, mount the disk, remove the file, etc?

**Comment by fivesixzero** [comment]
Oof, apologies for missing this one. Breaking `sudo` sucks. :( Apparently I ended up committing a `sudoers.d` file that was broken instead of the one that I'm actually using on my own systems.

Here's how I've fixed this when running into issues during development of this (and related) types of things where editing/testing `sudoers.d` files got hairy.

1. Shut down RPi and remove SD card
2. Mount SD card on another Linux system (or in a Linux VM with a direct connection)
3. Remove the offending file from the `rootfs/etc/sudoers.d` directory on the SD card
4. Put the SD card back in the RPi and start it up

After that it should be working fine.

As far as testing these changes, here's how I've done it while developing to avoid breaking `sudo` on a remote RPi.

1. Start a second terminal session and `sudo su` on that session
2. Edit or add `sudoers` entries in the original terminal session
3. Test `sudo` and, if it fails, revert using the still-open root shell in the other terminal session

And once you've added the `sudoers` entries, you can test to make sure that they work properly by running a `telegraf --test` as the `telegraf` user, like this.

```
sudo -u telegraf /usr/bin/telegraf --config telegraf.conf --test --input-filter exec
```

**Comment by manelpb** [comment]
Easier way to fix this issue is running this: 
```
pkttyagent -p $(echo $$) | pkexec rm /etc/sudoers.d/telegraf
```

This will ask the superuser (root) password and remove the file for you, without needing to mount the sdcard in a different machine
